/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SiuStock {
    }
}
declare global {
    interface HTMLSiuStockElement extends Components.SiuStock, HTMLStencilElement {
    }
    var HTMLSiuStockElement: {
        prototype: HTMLSiuStockElement;
        new (): HTMLSiuStockElement;
    };
    interface HTMLElementTagNameMap {
        "siu-stock": HTMLSiuStockElement;
    }
}
declare namespace LocalJSX {
    interface SiuStock {
    }
    interface IntrinsicElements {
        "siu-stock": SiuStock;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "siu-stock": LocalJSX.SiuStock & JSXBase.HTMLAttributes<HTMLSiuStockElement>;
        }
    }
}
