/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SiuSpinner {
    }
    interface SiuStock {
        "stockSymbol": string;
    }
    interface SiuStockFinder {
    }
}
export interface SiuStockFinderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSiuStockFinderElement;
}
declare global {
    interface HTMLSiuSpinnerElement extends Components.SiuSpinner, HTMLStencilElement {
    }
    var HTMLSiuSpinnerElement: {
        prototype: HTMLSiuSpinnerElement;
        new (): HTMLSiuSpinnerElement;
    };
    interface HTMLSiuStockElement extends Components.SiuStock, HTMLStencilElement {
    }
    var HTMLSiuStockElement: {
        prototype: HTMLSiuStockElement;
        new (): HTMLSiuStockElement;
    };
    interface HTMLSiuStockFinderElement extends Components.SiuStockFinder, HTMLStencilElement {
    }
    var HTMLSiuStockFinderElement: {
        prototype: HTMLSiuStockFinderElement;
        new (): HTMLSiuStockFinderElement;
    };
    interface HTMLElementTagNameMap {
        "siu-spinner": HTMLSiuSpinnerElement;
        "siu-stock": HTMLSiuStockElement;
        "siu-stock-finder": HTMLSiuStockFinderElement;
    }
}
declare namespace LocalJSX {
    interface SiuSpinner {
    }
    interface SiuStock {
        "stockSymbol"?: string;
    }
    interface SiuStockFinder {
        "onSiuSymbolSelected"?: (event: SiuStockFinderCustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "siu-spinner": SiuSpinner;
        "siu-stock": SiuStock;
        "siu-stock-finder": SiuStockFinder;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "siu-spinner": LocalJSX.SiuSpinner & JSXBase.HTMLAttributes<HTMLSiuSpinnerElement>;
            "siu-stock": LocalJSX.SiuStock & JSXBase.HTMLAttributes<HTMLSiuStockElement>;
            "siu-stock-finder": LocalJSX.SiuStockFinder & JSXBase.HTMLAttributes<HTMLSiuStockFinderElement>;
        }
    }
}
